# .github/workflows/build.yml

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Left half
          - board: xiao_ble
            shield: zonkey_left

          # Right half
          - board: xiao_ble
            shield: zonkey_right

          # Settings reset firmware
          - board: xiao_ble
            shield: settings_reset
