include:
  - board: seeeduino_xiao_ble
    shield: zonkey_L rgbled_adapter
    artifact-name: zonkey_L
  - board: seeeduino_xiao_ble
    shield: zonkey_R rgbled_adapter
    artifact-name: zonkey_R
  - board: seeeduino_xiao_ble
    shield: settings_reset
